#!/usr/bin/env bash
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-pushing_1-small_empty-singlefreq_4/config.yml -P logs/pretrained-pushing_1-small_empty-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-pushing_1-large_empty-singlefreq_4/config.yml -P logs/pretrained-pushing_1-large_empty-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-pushing_1-large_columns-singlefreq_4/config.yml -P logs/pretrained-pushing_1-large_columns-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-pushing_1-large_door-singlefreq_4/config.yml -P logs/pretrained-pushing_1-large_door-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-pushing_1-large_center-singlefreq_4/config.yml -P logs/pretrained-pushing_1-large_center-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-blowing_1-small_empty-multifreq_4/config.yml -P logs/pretrained-blowing_1-small_empty-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-blowing_1-large_empty-multifreq_4/config.yml -P logs/pretrained-blowing_1-large_empty-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-blowing_1-large_columns-multifreq_4/config.yml -P logs/pretrained-blowing_1-large_columns-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-blowing_1-large_door-multifreq_4/config.yml -P logs/pretrained-blowing_1-large_door-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/logs/pretrained-blowing_1-large_center-multifreq_4/config.yml -P logs/pretrained-blowing_1-large_center-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-pushing_1-small_empty-singlefreq_4/policy_00246000.pth.tar -P checkpoints/pretrained-pushing_1-small_empty-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-pushing_1-large_empty-singlefreq_4/policy_00246000.pth.tar -P checkpoints/pretrained-pushing_1-large_empty-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-pushing_1-large_columns-singlefreq_4/policy_00246000.pth.tar -P checkpoints/pretrained-pushing_1-large_columns-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-pushing_1-large_door-singlefreq_4/policy_00246000.pth.tar -P checkpoints/pretrained-pushing_1-large_door-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-pushing_1-large_center-singlefreq_4/policy_00246000.pth.tar -P checkpoints/pretrained-pushing_1-large_center-singlefreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-blowing_1-small_empty-multifreq_4/policy_00082000.pth.tar -P checkpoints/pretrained-blowing_1-small_empty-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-blowing_1-large_empty-multifreq_4/policy_00082000.pth.tar -P checkpoints/pretrained-blowing_1-large_empty-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-blowing_1-large_columns-multifreq_4/policy_00082000.pth.tar -P checkpoints/pretrained-blowing_1-large_columns-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-blowing_1-large_door-multifreq_4/policy_00082000.pth.tar -P checkpoints/pretrained-blowing_1-large_door-multifreq_4
wget -c https://learning-dynamic-manipulation.cs.princeton.edu/pretrained/checkpoints/pretrained-blowing_1-large_center-multifreq_4/policy_00082000.pth.tar -P checkpoints/pretrained-blowing_1-large_center-multifreq_4
