accumulate_lower_level_rewards: true
batch_size: 4
blowing_force: 0.35
blowing_fov: 15
blowing_num_wind_particles: 40
blowing_sim_step_target: 100
blowing_wind_particle_mass: 0.001
blowing_wind_particle_radius: 0.003
blowing_wind_particle_sparsity: 2
checkpoint_dir: null
checkpoint_freq: 1000
checkpoint_freq_mins: 30
checkpoint_path: null
checkpoints_dir: checkpoints
discount_factors:
- 0.75
distance_to_receptacle_map_scale: 0.25
env_name: small_empty
experiment_name: blowing_1-small_empty-local
exploration_frac: 0.1
final_exploration: 0.01
grad_norm_clipping: 100
inactivity_cutoff_per_robot: 5
learning_rate: 0.01
learning_starts_frac: 0.00025
log_dir: null
logs_dir: logs
num_input_channels: 4
num_low_steps_per_mid_step: 0
num_mid_steps_per_high_step: 0
num_objects: 50
num_parallel_collectors: null
object_mass: 9.0e-05
object_type: null
object_width: 0.012
obstacle_collision_penalty: 0.25
overhead_map_scale: 1.0
partial_rewards_scale: 2.0
policy_path: null
replay_buffer_size: 1000
robot_collision_penalty: 1.0
robot_config:
-   blowing_robot: 1
robot_map_scale: 1.0
room_length: 1.0
room_width: 0.5
run_name: null
shortest_path_map_scale: 0.25
show_gui: true
slowing_sim_step_target: 50
success_reward: 1.0
target_update_freq: 1000
total_timesteps: 20000
train_freq: 1
use_distance_to_receptacle_map: false
use_double_dqn: true
use_partial_observations: true
use_robot_map: true
use_shortest_path_map: true
use_shortest_path_movement: true
use_shortest_path_partial_rewards: true
use_shortest_path_to_receptacle_map: true
weight_decay: 0
